//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilet()
        {
            this.BiletFilmListe = new HashSet<BiletFilmListe>();
        }
    
        public int BiletId { get; set; }
        public Nullable<int> FilmId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> SalonId { get; set; }
        public Nullable<int> KoltukNum { get; set; }
        public string FilmAdi { get; set; }
        public IEnumerable<Koltuk> koltuklar { get; set; }

        public IEnumerable<Salon> salonlar { get; set; }

        public IEnumerable<Koltuk> secimKoltuklar { get; set; }

        public virtual Film Film { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiletFilmListe> BiletFilmListe { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
