//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiletFilmListe
    {
        public int BiletFilmListeId { get; set; }
        public Nullable<int> BiletId { get; set; }
        public Nullable<int> FilmId { get; set; }
    
        public virtual Bilet Bilet { get; set; }
        public virtual Film Film { get; set; }
    }
}
