//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Bilet = new HashSet<Bilet>();
            this.FilmSalonSeans = new HashSet<FilmSalonSeans>();
            this.BiletFilmListe = new HashSet<BiletFilmListe>();
        }
    
        public int FilmId { get; set; }
        public string FilmAdi { get; set; }
        public string FilmAciklamasi { get; set; }
        public string FilmSure { get; set; }
        public Nullable<decimal> FilmFiyat { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public string ResimYol { get; set; }
        public Nullable<int> TurId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual FilmTur FilmTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmSalonSeans> FilmSalonSeans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiletFilmListe> BiletFilmListe { get; set; }
        public virtual FilmTur FilmTur1 { get; set; }
    }
}
