//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaTicketProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koltuk
    {
        public int KoltukId { get; set; }
        public Nullable<int> KoltukNum { get; set; }
        public string KoltukSıra { get; set; }

        public bool rezerve { get; set; }
    }
}
